force-app/main/default/objects/BusRoute__c/BusRoute__c.object-meta.xml
<CustomObject>
    <label>Bus Route</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusRoute__c/fields/DurationInMinutes__c.field-meta.xml
<CustomField>
    <fullName>DurationInMinutes__c</fullName>
    <description>Difference in time between end/start time in minutes</description>
    <formula>IF(ISBLANK(EndTime__c),0, (EndTime__c-StartTime__c) / 60000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration In Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusRoute__c/fields/TotalStops__c.field-meta.xml
<CustomField>
    <fullName>TotalStops__c</fullName>
    <description>Calculates total number of bus stops in a route</description>
    <label>Total Stops</label>
    <summarizedField>Schedule__c.TimeToNextStop__c</summarizedField>
    <summaryForeignKey>Schedule__c.BusRoute__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BusStop__c/BusStop__c.object-meta.xml
<CustomObject>
    <description>Bus stop. May be a lot of stops in the route.</description>
    <label>Bus Stop</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusStops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>Time for every route on every stop.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TransportDAO.cls
public class TransportDAO {
    public static Integer getNumberOfStops(Id busRouteId){
        Decimal mydecval = [SELECT TotalStops__c FROM BusRoute__c WHERE Id = :busRouteId].TotalStops__c;
        Integer numberOfBusStops = mydecval.intValue();
        return numberOfBusStops;
    }
    public static Id getLongestByTimeRouteId(){
        List<BusRoute__c> routes = new List<BusRoute__c>([SELECT DurationInMinutes__c, id FROM BusRoute__c ORDER BY DurationInMinutes__c DESC NULLS LAST LIMIT 1]);
        return routes.get(0).id;
    }
    public static List<Schedule__c> getSchedules(Integer limits, Integer offset){
        List<Schedule__c> schedules = new List<Schedule__c>([SELECT id FROM Schedule__c LIMIT :limits OFFSET :offset]);
        return schedules;
    }
    public static List<BusStop__c> getBusStopsByIds(Set<Id> busStops){
        List<BusStop__c> stops = new List<BusStop__c>([SELECT id FROM BusStop__c WHERE Id IN :busStops]);
        return stops;
    }
    public static List<BusRoute__c> getBusRoutes(Set<Id> busStops){
       List<Schedule__c> sch = new List<Schedule__c>([SELECT BusRoute__c FROM Schedule__c WHERE BusStop__c IN :busStops]);
       Set<Id> routesId = new Set<Id>();
        for (Integer i=0; i<sch.size(); i++) {
            routesId.add(sch[i].BusRoute__c);
        }
        List<BusRoute__c> routes = new List<BusRoute__c>([SELECT id FROM BusRoute__c WHERE Id IN :routesId]);
        return routes;
    }
    public static Map<Id, Integer> getBusRoutesWithMinDuration(Integer limits){
        List<BusRoute__c> routeMinDuration = new List<BusRoute__c>([SELECT DurationInMinutes__c FROM BusRoute__c ORDER BY DurationInMinutes__c ASC NULLS FIRST LIMIT :limits]);
        Map<Id, Integer> minRoutes = new Map<Id, Integer>();
        for(BusRoute__c r: routeMinDuration) {
           minRoutes.put(r.id, r.DurationInMinutes__c.intValue());  
        }
        return minRoutes;
    }
    public static Map<Id, Integer> getBusRoutesWithMaxDuration(Integer limits){
        List<BusRoute__c> routeMaxDuration = new List<BusRoute__c>([SELECT DurationInMinutes__c FROM BusRoute__c ORDER BY DurationInMinutes__c DESC NULLS LAST LIMIT :limits]);
        Map<Id, Integer> maxRoutes = new Map<Id, Integer>();
        for(BusRoute__c r: routeMaxDuration) {
           maxRoutes.put(r.id, r.DurationInMinutes__c.intValue());  
        }
        return maxRoutes;
    }
}